apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    service: db
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
      - name: enekoperez/mi-proyecto:db-v1.0
        image: mariadb:10.8.2
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  
