apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production-gra
  template:
    metadata:
      name: grafana-pod
      labels:
        env: production-gra
    spec:
      containers:
        - name: grafana
          image: enekoperez/mi-proyecto:grafana-v1.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "yourpassword"
          volumeMounts:
            - name: gra-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: gra-storage
          persistentVolumeClaim:
            claimName: gra-pvc

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    env: production-gra
