apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    name: db-pod
    app: my-app
spec:
  containers:
    - name: mysql
      image: enekoperez/mi-proyecto:db-v1.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root123#"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "test123#"
        - name: MYSQL_DATABASE
          value: "database"
      volumeMounts:
        - name: mysql-storage  
          mountPath: /var/lib/mysql  
  volumes:
    - name: mysql-storage  
      persistentVolumeClaim:
        claimName: mysql-pvc  
