apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: production-py
  template:
    metadata:
      name: py-pod
      labels:
        env: production-py
    spec:
      containers:
        - name: python
          image: enekoperez/mi-proyecto:python-v1.0
