apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    service: web-service
spec:
  type: LoadBalancer
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector: 
    service: web      
