apiVersion: v1
kind: Pod
metadata: 
  name: web-app-pod
  labels:
    name: web-app-pod
    app: my-app
spec:
  containers:
    - name: web-app
      image: enekoperez/mi-proyecto:web-v1.0
      ports:
        - containerPort: 80
